### ISSUE TITLE
Automate welcome message on Discord

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/YouTube-operational-API#225]
Is it really wanted as there already is the [`#general-information`](https://discord.com/channels/933841502155706418/942945129025650739) channel?
But maybe it does not have everything that the welcome message contains.

Same comment applies to Discord: `Travian blockchained`, `Annihilation FR`, `Loria (serveur Dofus open-source)`, `Benjamin Loison's server`, `LemnosLife international`, `LemnosLife`, am I missing some (LemnosLife servers for instance).

**Comment by Benjamin-Loison** [comment]
Note that maybe automating with my account may get it banned, see [DiscordChatExporter](https://github.com/Tyrrrz/DiscordChatExporter).

**Comment by Benjamin-Loison** [comment]
I suspect web-scraping to be enough.

**Comment by Benjamin-Loison** [comment]
DuckDuckGo search *Python Discord bot listen to events*.
https://discordpy.readthedocs.io/en/stable/#getting-started
https://discordpy.readthedocs.io/en/stable/intro.html
[discord.py/tree/v2.5.0/examples](https://github.com/Rapptz/discord.py/tree/v2.5.0/examples)
[discord.py/blob/v2.5.0/examples/basic_bot.py](https://github.com/Rapptz/discord.py/blob/v2.5.0/examples/basic_bot.py)
https://discord.com/developers/docs/events/gateway#list-of-intents
https://discord.com/developers/applications/XXXXXXXXXXXXXXXXXX/bot

<details>
<summary>Python script:</summary>

```python
# This example requires the 'members' and 'message_content' privileged intents to function.

import discord
from discord.ext import commands

intents = discord.Intents.default()
intents.members = True
intents.message_content = True

bot = commands.Bot(command_prefix = '?', intents=intents)

@bot.event
async def on_ready():
    print(f'Logged in as {bot.user} (ID: {bot.user.id})')

@bot.command()
async def joined(ctx, member: discord.Member):
    """Says when a member joined."""
    print(f'{member.name} joined {discord.utils.format_dt(member.joined_at)}')
    #await ctx.send(f'{member.name} joined {discord.utils.format_dt(member.joined_at)}')

bot.run('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
```
</details>
<details>
<summary>Output:</summary>

```
2025-03-01 22:46:41 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "/home/benjamin_loison/a.py", line 24, in <module>
    bot.run('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/client.py", line 906, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/client.py", line 895, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/client.py", line 824, in start
    await self.connect(reconnect=reconnect)
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/client.py", line 748, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
```
</details>

**Comment by Benjamin-Loison** [comment]
*Reset Token* does not seem helpful to specify intents.

**Comment by Benjamin-Loison** [comment]
<details>
<summary>If comment <code>intents.message_content = True</code>, then get:</summary>

```
2025-03-01 23:11:46 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
2025-03-01 23:11:46 INFO     discord.client logging in using static token
2025-03-01 23:11:47 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX).
Logged in as LemnosLife#2322 (ID: 835851383096868874)
```
</details>

**Comment by Benjamin-Loison** [comment]
I enabled *Message Content Intent* but still face above *WARNING*.

**Comment by Benjamin-Loison** [comment]
Maybe regenerating the token help but may break my production...

**Comment by Benjamin-Loison** [comment]
The token is made of 3 parts separated by dots: `XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

The former is just base64 encoded of *Application ID* at https://discord.com/developers/applications/XXXXXXXXXXXXXXXXXX/information

For the 2 others I do not know.

**Comment by Benjamin-Loison** [comment]
*Bot Permissions* on https://discord.com/developers/applications/XXXXXXXXXXXXXXXXXX/bot seems more to help with math, than proceed to an actual action.

I do not have a fork of [discord.py](https://github.com/Rapptz/discord.py) on an other Git platform it seems.

**Comment by Benjamin-Loison** [comment]
Still have the issue after regenerating the token.

**Comment by Benjamin-Loison** [comment]
Still no `print` despite bringing back `intents.message_content = True`.

**Comment by Benjamin-Loison** [comment]
https://support-dev.discord.com/hc/en-us/articles/6205754771351-How-do-I-get-Privileged-Intents-for-my-bot

> You can apply for Privileged Intents once your app is installed in 75 or more servers, from your bot’s page on the Developer Portal.

So small developers can't prototype bots? How are bots supposed to start with such basic features missing?

**Comment by Benjamin-Loison** [comment]
https://discordpy.readthedocs.io/en/stable/discord.html

**Comment by Benjamin-Loison** [comment]
https://discordpy.readthedocs.io/en/stable/intents.html

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Python script:</summary>

```python
# This example requires the 'members' privileged intent to function.

import discord

class MyClient(discord.Client):
    async def on_ready(self):
        print(f'Logged in as {self.user} (ID: {self.user.id})')

    async def on_member_join(self, member):
        guild = member.guild
        to_send = f'Welcome {member.mention} to {guild.name}!'
        print(to_send)

intents = discord.Intents.default()
intents.members = True

client = MyClient(intents=intents)
client.run('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
```
</details>

still does not work as wanted.

**Comment by Benjamin-Loison** [comment]
*Server Settings* > *APPS* > *Integrations* > *Bots and Apps* should mention the bot it seems.

**Comment by Benjamin-Loison** [comment]
See [Improve_websites_thanks_to_open_source/issues/1442](https://codeberg.org/Benjamin_Loison/Improve_websites_thanks_to_open_source/issues/1442).

![Image](https://github.com/user-attachments/assets/e1d0a926-e69e-4fe1-be65-e68952ee32f7)

having officially a solution to automate my own account would be nice, instead of web-scrape and possibly be banned.

**Comment by Benjamin-Loison** [comment]
*OAuth2* > *Generated URL* with *bot* results in:

```
Welcome <@XXXXXXXXXXXXXXXXXX> to Test!
```

**Comment by Benjamin-Loison** [comment]
I would also like to have the opposite behavior.

DuckDuckGo search *on_member_join discord.py*.

**Comment by Benjamin-Loison** [comment]
https://discordpy.readthedocs.io/en/stable/api.html

**Comment by Benjamin-Loison** [comment]
See [OverClock3000_notifications](https://codeberg.org/Benjamin_Loison/OverClock3000_notifications) `notifyOnDiscordUsersLeaving.py`.

**Comment by Benjamin-Loison** [comment]
https://discordpy.readthedocs.io/en/stable/api.html#discord.Member

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Python script:</summary>

```python
import threading
import time

def threadFunction(threadFunctionId):
    while True:
        print(f'{threadFunctionId=}')
        time.sleep(1)

#threadFunction(0)

t1 = threading.Thread(target = threadFunction, args = (0,))
t2 = threading.Thread(target = threadFunction, args = (1,))

t1.start()
t2.start()

t1.join()
t2.join()
```
</details>

**Comment by Benjamin-Loison** [comment]
DuckDuckGo search *discord.py threading*.

<details>
<summary>Python script:</summary>

```python
import threading

TOKENS = [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
]

# https://discord.com/developers/applications/XXXXXXXXXXXXXXXXXX/bot > *Privileged Gateway Intents* > *Server Members Intent* is necessary
# No *Bot Permissions* needed.

class MyClient(discord.Client):
    async def on_ready(self):
        print(f'Logged in as {self.user} (ID: {self.user.id})')

    async def on_member_remove(self, member):
        guild = member.guild
        toSend = f'{member.name} ({member.mention}) left the guild {guild.name}!'
        print(toSend)

intents = discord.Intents(members = True, guilds = True)

def threadFunction(token):
    client = MyClient(intents = intents)
    client.run(token)

threads = []
for token in TOKENS:
    threads += [threading.Thread(target = threadFunction, args = (token,))]
    threads[-1].start()

for thread in threads:
    thread.join()
```
</details>
<details>
<summary>Output:</summary>

```
025-03-02 00:46:21 INFO     discord.client logging in using static token
2025-03-02 00:46:21 INFO     discord.client logging in using static token
2025-03-02 00:46:21 INFO     discord.client logging in using static token
2025-03-02 00:46:21 INFO     discord.client logging in using static token
2025-03-02 00:46:22 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX).
2025-03-02 00:46:22 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX).
2025-03-02 00:46:22 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY).
2025-03-02 00:46:22 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY).
Logged in as Benjamin Loison (Bot)#8550 (ID: 1345535277308969011)
Logged in as LemnosLife#2322 (ID: 835851383096868874)
test_de_benjamin_loison (<@811942490185793537>) left the guild LemnosLife!
test_de_benjamin_loison (<@811942490185793537>) left the guild YouTube operational API!
test_de_benjamin_loison (<@811942490185793537>) left the guild YouTube operational API!
```
</details>

```python
for thread in threads:
    thread.start()
```

and setting `MyClient` and `intents` definition in `threadFunction` do not help.

It does not seem that any of both in both guilds and it should not matter.

The aim is to avoid having two bots on a given guild.

**Comment by Benjamin-Loison** [comment]
An alternative is to run multiple times this script by providing as script argument the token.

**Comment by Benjamin-Loison** [comment]
If it was purely graphical I would not care much but I intend to send messages, so sending multiple times the same message is not appropriate.

**Comment by Benjamin-Loison** [comment]
DuckDuckGo search *discord.py event when a user join a vocal channel*.

**Comment by Benjamin-Loison** [comment]
DuckDuckGo search *discord.py with own account*.

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Output:</summary>

```
2025-03-02 01:39:15 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/http.py", line 828, in static_login
    data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/http.py", line 762, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/benjamin_loison/notifications/./notifyOnDiscordUsersLeaving.py", line 32, in <module>
    client.run(token)
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/client.py", line 906, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/client.py", line 895, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/client.py", line 823, in start
    await self.login(token)
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/client.py", line 652, in login
    data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/discord/http.py", line 832, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
```
</details>

**Comment by Benjamin-Loison** [comment]
https://www.reddit.com/r/discordapp/comments/196l9cu/discord_api_interact_with_own_account/
https://discord.com/developers/docs/topics/oauth2

**Comment by Benjamin-Loison** [comment]
> Developers must abide by the [terms of service](https://support-dev.discord.com/hc/articles/8562894815383-Discord-Developer-Terms-of-Service), which includes refraining from automating standard user accounts (generally called "self-bots") outside of the OAuth2/bot API.

Source: https://discord.com/developers/docs/topics/oauth2#bot-vs-user-accounts

**Comment by Benjamin-Loison** [comment]
[OverClock3000_notifications](https://codeberg.org/Benjamin_Loison/OverClock3000_notifications) `notifyOnNewDiscordActivity.py` uses Discord API like https://discord.com/developers/docs/resources/user#get-current-user.

However, I would like to listen to events like discord.py.

**Comment by Benjamin-Loison** [comment]
DuckDuckGo search *Discord API listen to events with user account*.

**Comment by Benjamin-Loison** [comment]
https://discordpy.readthedocs.io/en/latest/migrating.html#removal-of-support-for-user-accounts

**Comment by Benjamin-Loison** [comment]
[#issuecomment-2692492814](#issuecomment-2692492814) seems to be the way to go.

**Comment by Benjamin-Loison** [comment]
Can first verify that discord.py for user accounts works fine for my purpose.

**Comment by Benjamin-Loison** [comment]
For [OverClock3000_notifications](https://codeberg.org/Benjamin_Loison/OverClock3000_notifications) `notifyOnNewDiscordActivity.py` could as most as possible (that is for guilds accessible by bot account) leverage discord.py.

**Comment by Benjamin-Loison** [comment]
[discord.py-self/blob/bdc4542e6cf76f7e24192cce24d0676e8517c83a/README.rst#using-with-upstream](https://github.com/dolfies/discord.py-self/blob/bdc4542e6cf76f7e24192cce24d0676e8517c83a/README.rst#using-with-upstream)

[discord.py-self/blob/344e06f085dfa4835c747940054778ffe9610861/README.rst#notice](https://github.com/dolfies/discord.py-self/blob/344e06f085dfa4835c747940054778ffe9610861/README.rst#notice)

this branch seems correctly up-to-date but using another virtual environment in my case may be appropriate.

**Comment by Benjamin-Loison** [comment]
```bash
pip uninstall -y discord.py
```
<details>
<summary>Output:</summary>

```
Found existing installation: discord.py 2.5.0
Uninstalling discord.py-2.5.0:
  Successfully uninstalled discord.py-2.5.0
```
</details>

**Comment by Benjamin-Loison** [comment]
```bash
pip uninstall -y discord.py
```
```
WARNING: Skipping discord.py as it is not installed.
```

**Comment by Benjamin-Loison** [comment]
```bash
pip install discord.py-self
```
<details>
<summary>Output:</summary>

```
Collecting discord.py-self
  Downloading discord.py_self-2.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting aiohttp<4,>=3.7.4 (from discord.py-self)
  Downloading aiohttp-3.11.13-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (7.7 kB)
Collecting discord-protos<1.0.0 (from discord.py-self)
  Downloading discord-protos-0.0.2.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp<4,>=3.7.4->discord.py-self)
  Downloading aiohappyeyeballs-2.4.6-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp<4,>=3.7.4->discord.py-self)
  Downloading aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting attrs>=17.3.0 (from aiohttp<4,>=3.7.4->discord.py-self)
  Downloading attrs-25.1.0-py3-none-any.whl.metadata (10 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4,>=3.7.4->discord.py-self)
  Downloading frozenlist-1.5.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (13 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.7.4->discord.py-self)
  Downloading multidict-6.1.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.0 kB)
Collecting propcache>=0.2.0 (from aiohttp<4,>=3.7.4->discord.py-self)
  Downloading propcache-0.3.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (10 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4,>=3.7.4->discord.py-self)
  Downloading yarl-1.18.3-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.2/69.2 kB 8.4 MB/s eta 0:00:00
Collecting protobuf (from discord-protos<1.0.0->discord.py-self)
  Downloading protobuf-5.29.3-cp38-abi3-manylinux2014_aarch64.whl.metadata (592 bytes)
Collecting idna>=2.0 (from yarl<2.0,>=1.17.0->aiohttp<4,>=3.7.4->discord.py-self)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Downloading discord.py_self-2.0.1-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 52.7 MB/s eta 0:00:00
Downloading aiohttp-3.11.13-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 67.6 MB/s eta 0:00:00
Downloading aiohappyeyeballs-2.4.6-py3-none-any.whl (14 kB)
Downloading aiosignal-1.3.2-py2.py3-none-any.whl (7.6 kB)
Downloading attrs-25.1.0-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.2/63.2 kB 9.2 MB/s eta 0:00:00
Downloading frozenlist-1.5.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (282 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 282.6/282.6 kB 36.0 MB/s eta 0:00:00
Downloading multidict-6.1.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (130 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 18.6 MB/s eta 0:00:00
Downloading propcache-0.3.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.2/242.2 kB 33.1 MB/s eta 0:00:00
Downloading yarl-1.18.3-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (332 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.4/332.4 kB 40.0 MB/s eta 0:00:00
Downloading protobuf-5.29.3-cp38-abi3-manylinux2014_aarch64.whl (319 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.6/319.6 kB 32.2 MB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 10.3 MB/s eta 0:00:00
Building wheels for collected packages: discord-protos
  Building wheel for discord-protos (pyproject.toml) ... done
  Created wheel for discord-protos: filename=discord_protos-0.0.2-py3-none-any.whl size=14015 sha256=59ed7638baa329f70a98375cd4d9095e94d5ab68c48d5bae0133c0293262a467
  Stored in directory: /home/ubuntu/.cache/pip/wheels/97/d1/42/0fc10c1a7061a64bfbd0ab893204187390531272c79f1b8f65
Successfully built discord-protos
Installing collected packages: protobuf, propcache, multidict, idna, frozenlist, attrs, aiohappyeyeballs, yarl, discord-protos, aiosignal, aiohttp, discord.py-self
Successfully installed aiohappyeyeballs-2.4.6 aiohttp-3.11.13 aiosignal-1.3.2 attrs-25.1.0 discord-protos-0.0.2 discord.py-self-2.0.1 frozenlist-1.5.0 idna-3.10 multidict-6.1.0 propcache-0.3.0 protobuf-5.29.3 yarl-1.18.3
```
</details>

**Comment by Benjamin-Loison** [comment]
[discord.py-self/blob/bdc4542e6cf76f7e24192cce24d0676e8517c83a/README.rst#quick-example](https://github.com/dolfies/discord.py-self/blob/bdc4542e6cf76f7e24192cce24d0676e8517c83a/README.rst#quick-example)

<details>
<summary>Python script:</summary>

```python
import discord

class MyClient(discord.Client):
    async def on_ready(self):
        print('Logged on as', self.user)

    async def on_message(self, message):
        # only respond to ourselves
        if message.author != self.user:
            return

        print(f'{message.content=}')

client = MyClient()
client.run('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
```
</details>

[DiscordChatExporter/blob/f31e73bb7a392f450448625db9d69e20df75d634/.docs/Token-and-IDs.md#using-the-console](https://github.com/Tyrrrz/DiscordChatExporter/blob/f31e73bb7a392f450448625db9d69e20df75d634/.docs/Token-and-IDs.md#using-the-console)

<details>
<summary>Output:</summary>

```
2025-03-02 22:39:13 INFO     discord.client Logging in using static token.
2025-03-02 22:39:14 INFO     discord.http Found user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36, build number 373527.
2025-03-02 22:39:14 INFO     discord.gateway Connected to Gateway (Session ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX).
Logged on as test_de_benjamin_loison#0
```
</details>

**Comment by Benjamin-Loison** [comment]
> Prevents user account automation detection.

Source: [discord.py-self/blob/bdc4542e6cf76f7e24192cce24d0676e8517c83a/README.rst?plain=1#L39](https://github.com/dolfies/discord.py-self/blob/bdc4542e6cf76f7e24192cce24d0676e8517c83a/README.rst?plain=1#L39)

**Comment by Benjamin-Loison** [comment]
`if message.author != self.user:` was to blame that's weird, as it is not a note to self channel.

**Comment by Benjamin-Loison** [comment]
Concerning detection, see [Online_authentication_API/issues/73#issuecomment-2914131](https://codeberg.org/Benjamin_Loison/Online_authentication_API/issues/73#issuecomment-2914131).

**Comment by Benjamin-Loison** [comment]
I got 2 Matrix messages, see https://matrix.to/#/!sNARMdEsFZERaQAJzl:matrix.org/$dsMWIju4Ah77fInLWOdCsMqtc_MwwQt-nEQh_Ku2pRs.

```bash
ps aux | grep notifyOnDiscordUsersLeaving.py
```
<details>
<summary>Output:</summary>

```
benjami+     989  0.0  0.0   6932  2032 ?        Ss   Mar02   0:00 /usr/bin/bash /usr/bin/my_cron_shell -c cd notifications/ && ~/venv/bin/python3 notifyOnDiscordUsersLeaving.py 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
benjami+     994  0.0  0.0   6932  1944 ?        Ss   Mar02   0:00 /usr/bin/bash /usr/bin/my_cron_shell -c cd notifications/ && ~/venv/bin/python3 notifyOnDiscordUsersLeaving.py 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
benjami+     998  0.0  0.0   6932    16 ?        S    Mar02   0:00 /usr/bin/bash /usr/bin/my_cron_shell -c cd notifications/ && ~/venv/bin/python3 notifyOnDiscordUsersLeaving.py 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
benjami+    1000  0.0  0.5 214452 43604 ?        Sl   Mar02   0:17 /home/benjamin_loison/venv/bin/python3 notifyOnDiscordUsersLeaving.py XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
benjami+    1006  0.0  0.0   6932     8 ?        S    Mar02   0:00 /usr/bin/bash /usr/bin/my_cron_shell -c cd notifications/ && ~/venv/bin/python3 notifyOnDiscordUsersLeaving.py 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
benjami+    1011  0.0  0.5 215332 41028 ?        Sl   Mar02   0:17 /home/benjamin_loison/venv/bin/python3 notifyOnDiscordUsersLeaving.py XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
benjami+ 1298460  0.0  0.0   6440  2016 pts/0    S+   23:27   0:00 grep notifyOnDiscordUsersLeaving.py
```
</details>

```bash
kill 998
kill 1006
ps aux | grep notifyOnDiscordUsersLeaving.py
```
<details>
<summary>Output:</summary>

```
benjami+     989  0.0  0.0   6932  2032 ?        Ss   Mar02   0:00 /usr/bin/bash /usr/bin/my_cron_shell -c cd notifications/ && ~/venv/bin/python3 notifyOnDiscordUsersLeaving.py 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
benjami+     994  0.0  0.0   6932  1944 ?        Ss   Mar02   0:00 /usr/bin/bash /usr/bin/my_cron_shell -c cd notifications/ && ~/venv/bin/python3 notifyOnDiscordUsersLeaving.py 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
benjami+    1000  0.0  0.5 214452 43604 ?        Sl   Mar02   0:17 /home/benjamin_loison/venv/bin/python3 notifyOnDiscordUsersLeaving.py XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
benjami+    1011  0.0  0.5 215332 41028 ?        Sl   Mar02   0:17 /home/benjamin_loison/venv/bin/python3 notifyOnDiscordUsersLeaving.py XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
benjami+ 1304683  0.0  0.0   6440  2052 pts/0    S+   23:35   0:00 grep notifyOnDiscordUsersLeaving.py
```
</details>

**Comment by Benjamin-Loison** [comment]
Maybe related to [Benjamin_Loison/cron/issues/11](https://codeberg.org/Benjamin_Loison/cron/issues/11).

**Comment by Benjamin-Loison** [comment]
https://matrix.to/#/!sNARMdEsFZERaQAJzl:matrix.org/$I6F7YRVBCQts8oBZl9IK69w4YGI7_vL2ym1dotmOKUA seems to show that above  commands solved the duplicate issue.

**Comment by Benjamin-Loison** [comment]
Well according to `ps aux | grep Discord` looking normal, as the issue happened again, as I verified used tokens, it seems due to 2 bots being present, so I removed LemnosLife one.
