### ISSUE TITLE
Add `executable = '/usr/bin/bash'` to `subprocess.check_output` may be necessary to support `curl` `--data-raw $'...'`

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/YouTube-operational-API#293]
https://github.com/Benjamin-Loison/YouTube-operational-API/blob/d61488fbe0becf6d2a6ebc97761e5b87a8facd3f/tools/minimizeCURL.py#L43

See [the Unix Stack Exchange answer 115614](https://unix.stackexchange.com/a/115614).

**Comment by Benjamin-Loison** [comment]
It seems that currently the algorithm rebuilds the command as `--data-raw '$...'` which is an issue in the context of [Benjamin_Loison/OneDrive/issues/6](https://codeberg.org/Benjamin_Loison/OneDrive/issues/6).

**Comment by Benjamin-Loison** [comment]
Also before [YouTube-operational-API/blob/main/tools/minimizeCURL.py#L151-L228](https://github.com/Benjamin-Loison/YouTube-operational-API/blob/main/tools/minimizeCURL.py#L151-L228) have to be considered as it rebuilds incorrectly the command.

**Comment by Benjamin-Loison** [comment]
A shameful, probably introducing a security flaw, fix is:

```python
command = command.replace(" --data-raw '$", " --data-raw $'")
```

**Comment by Benjamin-Loison** [comment]
Related to #171.

**Comment by Benjamin-Loison** [comment]
Alternatively can replace `--data-raw $'...'` with `--data-raw "..."` it seems.

**Comment by Benjamin-Loison** [comment]
```bash
echo $'-----------------------------XXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\nContent-Disposition: form-data; name="no_individu"\r\n\r\nXXXXXX\r\n-----------------------------XXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\nContent-Disposition: form-data; name="acti"\r\n\r\nXX\r\n-----------------------------XXXXXXXXXXXXXXXXXXXXXXXXXXXX--\r\n'
```
```
-----------------------------XXXXXXXXXXXXXXXXXXXXXXXXXXXX
Content-Disposition: form-data; name="no_individu"

XXXXXX
-----------------------------XXXXXXXXXXXXXXXXXXXXXXXXXXXX
Content-Disposition: form-data; name="acti"

XX
-----------------------------XXXXXXXXXXXXXXXXXXXXXXXXXXXX--
```

I am unable to reproduce these new lines.

**Comment by Benjamin-Loison** [comment]
Related to [Webscrap_any_website/issues/29](https://codeberg.org/Benjamin_Loison/Webscrap_any_website/issues/29).

**Comment by Benjamin-Loison** [comment]
```python
import shlex

command = "curl --data-raw $'\''"

shlex.split(command)
```
```
Traceback (most recent call last):
  File "<tmp 6>", line 6, in <module>
    shlex.split(command)
  File "/usr/lib/python3.12/shlex.py", line 313, in split
    return list(lex)
  File "/usr/lib/python3.12/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.12/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.12/shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```

**Comment by Benjamin-Loison** [comment]
```python
help(shlex.split)
```
```
Help on function split in module shlex:

split(s, comments=False, posix=True)
    Split the string *s* using shell-like syntax.
```

**Comment by Benjamin-Loison** [comment]
https://docs.python.org/3/library/shlex.html#shlex.split

**Comment by Benjamin-Loison** [comment]
Removing `$` does not help.

```python
import shlex

command = "curl --data-raw $'\''"

print(shlex.split(command, posix = False))
```
```
['curl', '--data-raw', "$'''"]
```

**Comment by Benjamin-Loison** [comment]
```python
help(shlex.join)
```
```
Help on function join in module shlex:

join(split_command)
    Return a shell-escaped string from *split_command*.
```

**Comment by Benjamin-Loison** [comment]
```python
import shlex

command = "curl --data-raw $'\''"

commandSplitted = shlex.split(command, posix = False)
print(shlex.join(commandSplitted))
```
```
curl --data-raw '$'"'"''"'"''"'"''
```

**Comment by Benjamin-Loison** [comment]
```python
command = "curl --data-raw $'\''"
print(command)
```
```
curl --data-raw $'''
```

**Comment by Benjamin-Loison** [comment]
```python
import shlex

command = "curl --data-raw $'\\''"
# Equivalent to above `command`.
with open('curl.sh') as f:
    command = f.read()
print(command)

commandSplitted = shlex.split(command, posix = False)
print(shlex.join(commandSplitted))
print(' '.join(commandSplitted))
```
```
curl --data-raw $'\''

curl --data-raw '$'"'"'\'"'"''"'"''
curl --data-raw $'\''
```

**Comment by Benjamin-Loison** [comment]
Using `' '.join(...)` requires to manage quoting arguments on our own it seems.

**Comment by Benjamin-Loison** [comment]
```diff
diff --git a/tools/minimizeCURL.py b/tools/minimizeCURL.py
index 2b5a721..b64ec6a 100755
--- a/tools/minimizeCURL.py
+++ b/tools/minimizeCURL.py
@@ -31,7 +31,7 @@ wantedOutput = sys.argv[2].encode('utf-8')
 removeHeaders = True
 removeUrlParameters = True
 removeCookies = True
-removeRawData = True
+removeRawData = False#True
 
 # Pay attention to provide a command giving plaintext output, so might required to remove `Accept-Encoding` HTTPS header.
 with open(curlCommandFilePath) as f:
@@ -40,10 +40,13 @@ with open(curlCommandFilePath) as f:
 def executeCommand(command):
     # `stderr = subprocess.DEVNULL` is used to get rid of curl progress.
     # Could also add `-s` curl argument.
-    result = subprocess.check_output(command, shell = True, stderr = subprocess.DEVNULL)
+    result = subprocess.check_output(command, shell = True, stderr = subprocess.DEVNULL, executable = '/usr/bin/bash')
     return result
 
 def isCommandStillFine(command):
+    #command = command.replace(" --data-raw '$", " --data-raw $'")
+    #print(command)
+    #exit(1)
     result = executeCommand(command)
     return wantedOutput in result
 
@@ -62,41 +65,52 @@ if not isCommandStillFine(command):
     print('The wanted output isn\'t contained in the result of the original curl command!')
     exit(1)
 
+def splitCommand(command):
+    return shlex.split(command, posix = False)
+
+def joinSplittedCommand(spittedCommand):
+    return ' '.join(spittedCommand)
+    return shlex.join(spittedCommand)
+
 if removeHeaders:
     print('Removing headers')
 
     # Should try to minimize the number of requests done, by testing half of parameters at each request.
     while True:
         changedSomething = False
-        arguments = shlex.split(command)
+        arguments = splitCommand(command)
         for argumentsIndex in range(len(arguments) - 1):
             argument, nextArgument = arguments[argumentsIndex : argumentsIndex + 2]
             if argument == '-H':
                 previousCommand = command
                 del arguments[argumentsIndex : argumentsIndex + 2]
-                command = shlex.join(arguments)
+                command = joinSplittedCommand(arguments)
+                #print(command)
+                #exit(1)
                 if isCommandStillFine(command):
                     printThatCommandIsStillFine(command)
                     changedSomething = True
                     break
                 else:
                     command = previousCommand
-                    arguments = shlex.split(command)
+                    arguments = splitCommand(command)
         if not changedSomething:
             break
 
 if removeUrlParameters:
     print('Removing URL parameters')
 
-    arguments = shlex.split(command)
+    arguments = splitCommand(command)
     for argumentsIndex, argument in enumerate(arguments):
-        if argument.startswith('http'):
+        if argument.startswith("'http"):
             urlIndex = argumentsIndex
+            #arguments[urlIndex] = arguments[urlIndex][1:-1]
             break
 
     url = arguments[urlIndex]
     while True:
         changedSomething = False
+        url = url[1:-1]
         urlParsed = urlparse(url)
         query = parse_qs(urlParsed.query)
         for key in list(query):
@@ -104,8 +118,8 @@ if removeUrlParameters:
             del query[key]
             # Make a function with below code.
             url = urlParsed._replace(query = '&'.join([f'{quote_plus(parameter)}={quote_plus(query[parameter][0])}' for parameter in query])).geturl()
-            arguments[urlIndex] = url
-            command = shlex.join(arguments)
+            arguments[urlIndex] = shlex.quote(url)
+            command = joinSplittedCommand(arguments)
             if isCommandStillFine(command):
                 printThatCommandIsStillFine(command)
                 changedSomething = True
@@ -113,8 +127,8 @@ if removeUrlParameters:
             else:
                 query = previousQuery
                 url = urlParsed._replace(query = '&'.join([f'{quote_plus(parameter)}={quote_plus(query[parameter][0])}' for parameter in query])).geturl()
-                arguments[urlIndex] = url
-                command = shlex.join(arguments)
+                arguments[urlIndex] = shlex.quote(url)
+                command = joinSplittedCommand(arguments)
         if not changedSomething:
             break
 
@@ -125,7 +139,7 @@ if removeCookies:
     COOKIES_PREFIX_LEN = len(COOKIES_PREFIX)
 
     cookiesIndex = None
-    arguments = shlex.split(command)
+    arguments = splitCommand(command)
     for argumentsIndex, argument in enumerate(arguments):
         # For Chromium support:
         if argument[:COOKIES_PREFIX_LEN].title() == COOKIES_PREFIX:
@@ -142,7 +156,7 @@ if removeCookies:
                 cookiesParsedCopy = cookiesParsed[:]
                 del cookiesParsedCopy[cookiesParsedIndex]
                 arguments[cookiesIndex] = COOKIES_PREFIX + '; '.join(cookiesParsedCopy)
-                command = shlex.join(arguments)
+                command = joinSplittedCommand(arguments)
                 if isCommandStillFine(command):
                     printThatCommandIsStillFine(command)
                     changedSomething = True
@@ -150,7 +164,7 @@ if removeCookies:
                     break
                 else:
                     arguments[cookiesIndex] = COOKIES_PREFIX + '; '.join(cookiesParsed)
-                    command = shlex.join(arguments)
+                    command = joinSplittedCommand(arguments)
             if not changedSomething:
                 break
 
@@ -159,7 +173,7 @@ if removeRawData:
 
     rawDataIndex = None
     isJson = False
-    arguments = shlex.split(command)
+    arguments = splitCommand(command)
     for argumentsIndex, argument in enumerate(arguments):
         if argumentsIndex > 0 and arguments[argumentsIndex - 1] == '--data-raw':
             rawDataIndex = argumentsIndex
@@ -182,7 +196,7 @@ if removeRawData:
                     rawDataPartsCopy = copy.deepcopy(rawDataParts)
                     del rawDataPartsCopy[rawDataPartsIndex]
                     arguments[rawDataIndex] = '&'.join(rawDataPartsCopy)
-                    command = shlex.join(arguments)
+                    command = joinSplittedCommand(arguments)
                     if isCommandStillFine(command):
                         printThatCommandIsStillFine(command)
                         changedSomething = True
@@ -190,7 +204,7 @@ if removeRawData:
                         break
                     else:
                         arguments[rawDataIndex] = '&'.join(rawDataParts)
-                        command = shlex.join(arguments)
+                        command = joinSplittedCommand(arguments)
                 if not changedSomething:
                     break
         # JSON recursive case.
@@ -229,7 +243,7 @@ if removeRawData:
                     del entry[lastPathPart]
                     # Test if the removed entry was necessary.
                     arguments[rawDataIndex] = json.dumps(rawDataParsedCopy)
-                    command = shlex.join(arguments)
+                    command = joinSplittedCommand(arguments)
                     # (1) If it was unnecessary, then reconsider paths excluding possible children paths of this unnecessary entry, ensuring optimized complexity it seems.
                     if isCommandStillFine(command):
                         printThatCommandIsStillFine(command)
@@ -239,7 +253,7 @@ if removeRawData:
                     # If it was necessary, we consider possible children paths of this necessary entry and other paths.
                     else:
                         arguments[rawDataIndex] = json.dumps(rawDataParsed)
-                        command = shlex.join(arguments)
+                        command = joinSplittedCommand(arguments)
                 # If a loop iteration considering all paths, does not change anything, then the request cannot be minimized further.
                 if not changedSomething:
                     break
```

**Comment by Benjamin-Loison** [comment]
For big file modified above diff with:

<details>
<summary>Output:</summary>

```diff
diff --git a/tools/minimizeCURL.py b/tools/minimizeCURL.py
index 2b5a721..6e281ea 100755
--- a/tools/minimizeCURL.py
+++ b/tools/minimizeCURL.py
@@ -31,7 +31,7 @@ wantedOutput = sys.argv[2].encode('utf-8')
 removeHeaders = True
 removeUrlParameters = True
 removeCookies = True
-removeRawData = True
+removeRawData = False
 
 # Pay attention to provide a command giving plaintext output, so might required to remove `Accept-Encoding` HTTPS header.
 with open(curlCommandFilePath) as f:
@@ -40,7 +40,12 @@ with open(curlCommandFilePath) as f:
 def executeCommand(command):
     # `stderr = subprocess.DEVNULL` is used to get rid of curl progress.
     # Could also add `-s` curl argument.
-    result = subprocess.check_output(command, shell = True, stderr = subprocess.DEVNULL)
+    INTERMEDIARY_CURL_FILE_PATH = 'intermediary_curl.sh'
+    with open(INTERMEDIARY_CURL_FILE_PATH, 'w') as f:
+        f.write(command)
+    result = subprocess.check_output(f'bash {INTERMEDIARY_CURL_FILE_PATH}', shell = True, stderr = subprocess.DEVNULL)
+    #print(result)
+    #exit(1)
     return result
 
 def isCommandStillFine(command):
@@ -56,6 +61,13 @@ def printThatCommandIsStillFine(command):
 # For Chromium support:
 command = command.replace(' \\\n ', '')
 
+def splitCommand(command):
+    return shlex.split(command, posix = False)
+
+def joinSplittedCommand(spittedCommand):
+    return ' '.join(spittedCommand)
+    return shlex.join(spittedCommand)
+
 print(f'Initial command length: {getCommandLengthFormatted(command)}.')
 # To verify that the user provided the correct `wantedOutput` to keep during the minimization.
 if not isCommandStillFine(command):
@@ -68,35 +80,37 @@ if removeHeaders:
     # Should try to minimize the number of requests done, by testing half of parameters at each request.
     while True:
         changedSomething = False
-        arguments = shlex.split(command)
+        arguments = splitCommand(command)
         for argumentsIndex in range(len(arguments) - 1):
             argument, nextArgument = arguments[argumentsIndex : argumentsIndex + 2]
             if argument == '-H':
                 previousCommand = command
                 del arguments[argumentsIndex : argumentsIndex + 2]
-                command = shlex.join(arguments)
+                command = joinSplittedCommand(arguments)
                 if isCommandStillFine(command):
                     printThatCommandIsStillFine(command)
                     changedSomething = True
                     break
                 else:
                     command = previousCommand
-                    arguments = shlex.split(command)
+                    arguments = splitCommand(command)
         if not changedSomething:
             break
 
 if removeUrlParameters:
     print('Removing URL parameters')
 
-    arguments = shlex.split(command)
+    arguments = splitCommand(command)
     for argumentsIndex, argument in enumerate(arguments):
-        if argument.startswith('http'):
+        if argument.startswith("'http"):
             urlIndex = argumentsIndex
+            #arguments[urlIndex] = arguments[urlIndex][1:-1]
             break
 
     url = arguments[urlIndex]
     while True:
         changedSomething = False
+        url = url[1:-1]
         urlParsed = urlparse(url)
         query = parse_qs(urlParsed.query)
         for key in list(query):
@@ -104,8 +118,8 @@ if removeUrlParameters:
             del query[key]
             # Make a function with below code.
             url = urlParsed._replace(query = '&'.join([f'{quote_plus(parameter)}={quote_plus(query[parameter][0])}' for parameter in query])).geturl()
-            arguments[urlIndex] = url
-            command = shlex.join(arguments)
+            arguments[urlIndex] = shlex.quote(url)
+            command = joinSplittedCommand(arguments)
             if isCommandStillFine(command):
                 printThatCommandIsStillFine(command)
                 changedSomething = True
@@ -113,8 +127,8 @@ if removeUrlParameters:
             else:
                 query = previousQuery
                 url = urlParsed._replace(query = '&'.join([f'{quote_plus(parameter)}={quote_plus(query[parameter][0])}' for parameter in query])).geturl()
-                arguments[urlIndex] = url
-                command = shlex.join(arguments)
+                arguments[urlIndex] = shlex.quote(url)
+                command = joinSplittedCommand(arguments)
         if not changedSomething:
             break
 
@@ -125,7 +139,7 @@ if removeCookies:
     COOKIES_PREFIX_LEN = len(COOKIES_PREFIX)
 
     cookiesIndex = None
-    arguments = shlex.split(command)
+    arguments = splitCommand(command)
     for argumentsIndex, argument in enumerate(arguments):
         # For Chromium support:
         if argument[:COOKIES_PREFIX_LEN].title() == COOKIES_PREFIX:
@@ -142,7 +156,7 @@ if removeCookies:
                 cookiesParsedCopy = cookiesParsed[:]
                 del cookiesParsedCopy[cookiesParsedIndex]
                 arguments[cookiesIndex] = COOKIES_PREFIX + '; '.join(cookiesParsedCopy)
-                command = shlex.join(arguments)
+                command = joinSplittedCommand(arguments)
                 if isCommandStillFine(command):
                     printThatCommandIsStillFine(command)
                     changedSomething = True
@@ -150,7 +164,7 @@ if removeCookies:
                     break
                 else:
                     arguments[cookiesIndex] = COOKIES_PREFIX + '; '.join(cookiesParsed)
-                    command = shlex.join(arguments)
+                    command = joinSplittedCommand(arguments)
             if not changedSomething:
                 break
 
@@ -159,7 +173,7 @@ if removeRawData:
 
     rawDataIndex = None
     isJson = False
-    arguments = shlex.split(command)
+    arguments = splitCommand(command)
     for argumentsIndex, argument in enumerate(arguments):
         if argumentsIndex > 0 and arguments[argumentsIndex - 1] == '--data-raw':
             rawDataIndex = argumentsIndex
@@ -182,7 +196,7 @@ if removeRawData:
                     rawDataPartsCopy = copy.deepcopy(rawDataParts)
                     del rawDataPartsCopy[rawDataPartsIndex]
                     arguments[rawDataIndex] = '&'.join(rawDataPartsCopy)
-                    command = shlex.join(arguments)
+                    command = joinSplittedCommand(arguments)
                     if isCommandStillFine(command):
                         printThatCommandIsStillFine(command)
                         changedSomething = True
@@ -190,7 +204,7 @@ if removeRawData:
                         break
                     else:
                         arguments[rawDataIndex] = '&'.join(rawDataParts)
-                        command = shlex.join(arguments)
+                        command = joinSplittedCommand(arguments)
                 if not changedSomething:
                     break
         # JSON recursive case.
@@ -229,7 +243,7 @@ if removeRawData:
                     del entry[lastPathPart]
                     # Test if the removed entry was necessary.
                     arguments[rawDataIndex] = json.dumps(rawDataParsedCopy)
-                    command = shlex.join(arguments)
+                    command = joinSplittedCommand(arguments)
                     # (1) If it was unnecessary, then reconsider paths excluding possible children paths of this unnecessary entry, ensuring optimized complexity it seems.
                     if isCommandStillFine(command):
                         printThatCommandIsStillFine(command)
@@ -239,7 +253,7 @@ if removeRawData:
                     # If it was necessary, we consider possible children paths of this necessary entry and other paths.
                     else:
                         arguments[rawDataIndex] = json.dumps(rawDataParsed)
-                        command = shlex.join(arguments)
+                        command = joinSplittedCommand(arguments)
                 # If a loop iteration considering all paths, does not change anything, then the request cannot be minimized further.
                 if not changedSomething:
                     break
```
</details>

**Comment by Benjamin-Loison** [comment]
*Copy as {PowerShell,Fetch}* do not seem to help. What about Windows?

**Comment by Benjamin-Loison** [comment]
DuckDuckGo and Google search *Command POSIX to Windows converter* do not return relevant results it seems.

**Comment by Benjamin-Loison** [comment]
Note that `echo $"a\nb"` does not work while `echo $'a\nb'` does.

**Comment by Benjamin-Loison** [comment]
Maybe latest Python version of `shlex` supports this feature.

**Comment by Benjamin-Loison** [comment]
Can maybe somehow not need `$'...'` by expand newlines (but does not seem to apply to other usages of `$'...'`) or use a given file for `--data-raw` with `@`.

**Comment by Benjamin-Loison** [comment]
```python
COMMAND = "echo $'a\\nb'"
print(COMMAND)
print(shlex.split(COMMAND))
```
```
echo $'a\nb'
['echo', '$a\\nb']
```

```python
COMMAND = "echo '$a\\nb'"
print(COMMAND)
print(shlex.split(COMMAND))
```
```
echo '$a\nb'
['echo', '$a\\nb']
```

```bash
echo '$a\nb'
```
```
$a\nb
```

```python
COMMAND = "echo $'a\\nb'"
print(COMMAND)
print(shlex.split(COMMAND, posix = False))
```
```
echo $'a\nb'
['echo', "$'a\\nb'"]
```

```python
COMMAND = "echo '$a\\nb'"
print(COMMAND)
print(shlex.split(COMMAND, posix = False))
```
```
echo '$a\nb'
['echo', "'$a\\nb'"]
```

**Comment by Benjamin-Loison** [comment]
In the case of [Online authentication API](https://codeberg.org/Benjamin_Loison/Online_authentication_API), this issue may be due to my complex passwords, using, if possible, passwords without special characters may help.

**Comment by Benjamin-Loison** [comment]
For reference: *dollar*.

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Python script:</summary>

```python
import shlex
import pyperclip

pyperclip.copy(shlex.quote(pyperclip.paste()))
```
</details>

helps.

**Comment by Benjamin-Loison** [comment]
https://chat.mistral.ai/chat/a4195a59-0e41-4d45-8d4b-29fff31dfe93

https://chatgpt.com/share/69dd1200-383c-8333-943b-b500aa35d615

[idank/bashlex](https://github.com/idank/bashlex) has 632 stars and last commit was 2 years ago.

[idank/bashlex/blob/3f6b76c4c8462f4b90d9b1c73a555c45cde42f62/README.md](https://github.com/idank/bashlex/blob/3f6b76c4c8462f4b90d9b1c73a555c45cde42f62/README.md) shows `split` example.

<details>
<summary>Python script:</summary>

```python
import subprocess

cmd = "command_0 $'argument_0_requiring_dollar_prefix' argument_1"

# Ask bash to parse and print arguments safely
parsed = subprocess.check_output(
    ["bash", "-c", f"printf '%s\n' {cmd}"],
    text=True
).splitlines()

parsed[0] = "command_1"

print(parsed)
```
</details>

```python
['command_1', 'argument_0_requiring_dollar_prefix', 'argument_1']
```

If remove `text=True`:

```python
['command_1', b'argument_0_requiring_dollar_prefix', b'argument_1']
```

which is still incorrect.

```bash
apt list | grep bashlex
```

does not return anything on Ubuntu 24 Oracle VPS.

```bash
pip install bashlex
```
<details>
<summary>Output:</summary>

```
Collecting bashlex
  Downloading bashlex-0.18-py2.py3-none-any.whl.metadata (1.1 kB)
Downloading bashlex-0.18-py2.py3-none-any.whl (69 kB)
Installing collected packages: bashlex
Successfully installed bashlex-0.18
```
</details>

```bash
python3 -c 'import bashlex; print(list(bashlex.split("command_0 $'argument_0_requiring_dollar_prefix' argument_1")))'
```
```python
['command_0', '$argument_0_requiring_dollar_prefix', 'argument_1']
```

No matter `text=True` `cmd = "command_0 $'a\r\nb' argument_1"` and `cmd = "command_0 $'a\nb' argument_1"` I get `['command_1', 'a', 'b', 'argument_1']`.

```bash
python3 -c 'import bashlex; print(list(bashlex.split("command_0 $'a\rb\nc' argument_1")))'
```
```
['command_0', '$arbnc', 'argument_1']
```

So none of both ChatGPT solutions do not work it seems.
