### ISSUE TITLE
YT operational API Search endpoint not able to fetch more than 500 results

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/YouTube-operational-API#4]
YouTube Data API v3 [Search: list](https://developers.google.com/youtube/v3/docs/search/list) endpoint is limited to 500 results:
> **Note**: Search results are constrained to a maximum of 500 videos if your request specifies a value for the **channelId** parameter and sets the [type](https://developers.google.com/youtube/v3/docs/search/list#type) parameter value to **video**, but it does not also set one of the [forContentOwner](https://developers.google.com/youtube/v3/docs/search/list#forContentOwner), [forDeveloper](https://developers.google.com/youtube/v3/docs/search/list#forDeveloper), or [forMine](https://developers.google.com/youtube/v3/docs/search/list#forMine) filters.

Source: [Search: list#channelId](https://developers.google.com/youtube/v3/docs/search/list#channelId)

Is seems possible to fetch more than 500 results from the YT UI (would need a small tool checking that from source code after having scrolled manually), this issue shouldn't come from my reverse-engineering code.

If achieved that would help:
- https://stackoverflow.com/q/72438701/7123660
- 808arc#8280

```
import requests, json

def get(url):
    return requests.get(url).text

pageToken = ''

ids = []

while True:
    url = 'https://yt.lemnoslife.com/search?part=id&q=hololive&type=video'
    if pageToken != '':
        url += '&pageToken=' + pageToken
    content = get(url)
    #print(content)
    data = json.loads(content)
    pageToken = data['nextPageToken']
    items = data['items']
    for item in items:
        id = item['id']
        if not id in ids:
            ids += [id]
    print(len(ids))

# reached 437 before KeyError: 'nextPageToken'
```

Related code: https://github.com/Benjamin-Loison/YouTube-operational-API/blob/9b5a7805834fd56f12afc1fb55e439a68a5a787f/search.php#L105-L117

**Comment by Benjamin-Loison** [comment]
YouTube UI search by query term (`Test` here) when filtering for only retrieving videos stopped after `549` results (filtered `ago` as a whole word and filtering with `view` gives a similar result)...

When not filtering for only retrieving videos stopped after `654` results (filtered `ago` as a whole word).
Filtering with:
- `view` gives 702 matches
- `VIEW FULL PLAYLIST` gives 2 matches, so can guess there are this number of playlists
- `subscriber` gives 44 matches, so can guess there are this number of channels

So this issue can't be solved easily AFAIK as _the issue_ (limitation in fact) is on YouTube end.

**Comment by Benjamin-Loison** [comment]
Could give a try forcing YouTube Data API v3 Search: list endpoint by providing a modified page token after having reverse-engineered it as it doesn't contain randomness AFAIK.

**Comment by Benjamin-Loison** [comment]
Similar issue: https://stackoverflow.com/questions/76699812/how-do-i-get-youtube-community-posts-older-than-200#comment135264020_76699812

**Comment by Benjamin-Loison** [comment]
#190 could help.

**Comment by Benjamin-Loison** [comment]
```json
import requests
import json

def get(url):
    return 

pageToken = ''
ids = set()
url = 'https://yt.lemnoslife.com/noKey/search'
params = {
    'q': 'test',
    'type': 'video',
    'maxResults': 50,
}

while True:
    params['pageToken'] = pageToken
    data = requests.get(url, params = params).json()
    pageToken = data['nextPageToken']
    items = data['items']
    for item in items:
        id_ = item['id']['videoId']
        ids.add(id_)
    print(len(ids))

# reached 518 before KeyError: 'nextPageToken'
```

**Comment by Benjamin-Loison** [comment]
```bash
protoc --help
```

```bash
mkdir test/ && protoc test.proto --php_out test/
```

```bash
php a.php
```
```
PHP Fatal error:  Uncaught Error: Class "GPBMetadata\A" not found in /home/benjamin/protobuf/message.php:34
Stack trace:
#0 /home/benjamin/protobuf/a.php(7): message->__construct()
#1 {main}
  thrown in /home/benjamin/protobuf/message.php on line 34
```

Commenting `\GPBMetadata\A::initOnce();` leads to:

```
PHP Fatal error:  Uncaught InvalidArgumentException: message is not found in descriptor pool. Only generated classes may derive from Message. in /home/benjamin/protobuf/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:74
Stack trace:
#0 /home/benjamin/protobuf/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(55): Google\Protobuf\Internal\Message->initWithGeneratedPool()
#1 /home/benjamin/protobuf/message.php(35): Google\Protobuf\Internal\Message->__construct()
#2 /home/benjamin/protobuf/a.php(7): message->__construct()
#3 {main}
  thrown in /home/benjamin/protobuf/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php on line 74
```

**Comment by Benjamin-Loison** [comment]
Related to [Webscrap_any_website/issues/58](https://codeberg.org/Benjamin_Loison/Webscrap_any_website/issues/58).
